# Parameters configuration file for the pedigree analysis pipeline

# If you do not specify regions, set it to NO_FILE.
regions: "${projectDir}/resources/NO_FILE"
# If you do not specify known_sites, set it to NO_FILE.
known_sites: "${projectDir}/resources/NO_FILE"
# If you do not specify life_history_file, set it to NO_FILE.
lh_file: "${projectDir}/resources/NO_FILE"

# Output
outdir: "results"

# Variant caller
caller: "bcftools" # Option: bcftools, freebayes, gatk

# Trimmomatic
trim_leading: 20            # Cut bases off the start of a read, if below a threshold quality
trim_trailing: 20           # Cut bases off the end of a read, if below a threshold quality
trim_slidingwindow: "4:20"  # Perform a sliding window trimming, cutting once the average quality within the window falls below a threshold.
trim_minlen: 100            # Drop the read if it is below a specified length
trim_extra: ""              # Additional parameters for Trimmomatic (e.g., "HEADCROP:10" )

# SAMtools
samtools_Q: 30
samtools_F: 256

# VCFtools
vcftools_min_alleles: 2
vcftools_max_alleles: 2
vcftools_min_meanDP: 10
vcftools_max_meanDP: 300
vcftools_ind_max_miss: 0.1
vcftools_site_max_miss: 0.1

# Genotype quality checks
ad_plot_max_points: 0
