# Parameters configuration file for the pedigree analysis pipeline

# If you do not specify regions, set it to NO_FILE.
regions: "${projectDir}/resources/NO_FILE"
# If you do not specify known_sites, set it to NO_FILE.
known_sites: "${projectDir}/resources/NO_FILE"
# If you do not specify life_history_file, set it to NO_FILE.
lh_file: "${projectDir}/resources/NO_FILE"

# Output
outdir: "results"

# Variant caller
caller: "bcftools" # Option: bcftools, freebayes, gatk

# Trimmomatic
trim_threads: 8
trim_extra: ""

# BWA-MEM
bwa_threads: 8
bwa_mem: "16 GB"
bwa_time: "8h"

# SAMtools
samtools_Q: 30
samtools_F: 256

# BCFtools
bcftools_threads: 8
bcftools_mem: "16 GB"
bcftools_time: "8h"

# GATK
gatk_threads: 8
gatk_mem: "16 GB"
gatk_time: "8h"

# FreeBayes
freebayes_threads: 8
freebayes_mem: "16 GB"
freebayes_time: "8h"

# VCFtools
vcftools_min_alleles: 2
vcftools_max_alleles: 2
vcftools_min_meanDP: 10
vcftools_ind_max_miss: 0.1
vcftools_site_max_miss: 0.1

# Genotype quality checks
ad_plot_max_points: 0
